/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.animalclinic.view;

import lk.ijse.animalclinic.view.panels.AddAppointmentPanel;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ButtonType;
import javax.swing.JOptionPane;
import lk.ijse.animalclinic.common.IDGenarator;
import lk.ijse.animalclinic.common.Validation;
import lk.ijse.animalclinic.controller.OwnerController;
import lk.ijse.animalclinic.core.dto.OwnerDTO;

/**
 *
 * @author chamindu
 */
public class DialogFormAddOwner extends javax.swing.JDialog {

    /**
     * Creates new form AddOwner
     */
    public DialogFormAddOwner(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getOwnerID();;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtOwnerID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTelNo = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        btnAddOwner = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        btnCancel = new javax.swing.JLabel();
        txtLastName = new org.jdesktop.swingx.JXTextField();
        txtFirstName = new org.jdesktop.swingx.JXTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel8.setBackground(new java.awt.Color(250, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 135, 173), 5));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(29, 120, 156));
        jLabel41.setText("Add New Owner");
        jPanel8.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(40, 135, 173));
        jLabel27.setText("Owner ID    -");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 30));

        txtOwnerID.setEditable(false);
        txtOwnerID.setBackground(new java.awt.Color(250, 255, 255));
        txtOwnerID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtOwnerID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(txtOwnerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 220, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(40, 135, 173));
        jLabel15.setText("Tel.No       -");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 30));

        txtTelNo.setBackground(new java.awt.Color(250, 255, 255));
        txtTelNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTelNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelNoFocusLost(evt);
            }
        });
        txtTelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelNoActionPerformed(evt);
            }
        });
        jPanel8.add(txtTelNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 220, 30));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(40, 135, 173));
        jLabel45.setText("NIC              -");
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, 30));

        txtNIC.setBackground(new java.awt.Color(250, 255, 255));
        txtNIC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNIC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNIC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNICFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNICFocusLost(evt);
            }
        });
        txtNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNICActionPerformed(evt);
            }
        });
        jPanel8.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 220, 30));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(40, 135, 173));
        jLabel46.setText("Address       -");
        jPanel8.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 110, 30));

        btnAddOwner.setBackground(new java.awt.Color(102, 102, 102));
        btnAddOwner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddOwner.setForeground(new java.awt.Color(255, 255, 255));
        btnAddOwner.setText("+ New Owner");
        btnAddOwner.setOpaque(true);
        btnAddOwner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddOwnerMouseClicked(evt);
            }
        });
        jPanel8.add(btnAddOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, 130, 50));

        txtAddress.setBackground(new java.awt.Color(250, 255, 255));
        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAddress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 950, 30));

        btnCancel.setBackground(new java.awt.Color(102, 102, 102));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("       Cancel");
        btnCancel.setOpaque(true);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        jPanel8.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 340, 130, 50));

        txtLastName.setBackground(new java.awt.Color(250, 255, 255));
        txtLastName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtLastName.setPrompt("                     Last Name");
        txtLastName.setPromptForeground(new java.awt.Color(0, 0, 0));
        txtLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLastNameFocusLost(evt);
            }
        });
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        jPanel8.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 690, 30));

        txtFirstName.setBackground(new java.awt.Color(250, 255, 255));
        txtFirstName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtFirstName.setPrompt("           First Name");
        txtFirstName.setPromptForeground(new java.awt.Color(0, 0, 0));
        txtFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusLost(evt);
            }
        });
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        jPanel8.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 220, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(40, 135, 173));
        jLabel14.setText("Name           -");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddOwnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddOwnerMouseClicked
        if (txtTelNo.getText().isEmpty() || txtAddress.getText().isEmpty() || txtFirstName.getText().isEmpty() || txtLastName.getText().isEmpty() || txtNIC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all");
        } else {
            OwnerDTO owner = new OwnerDTO(txtOwnerID.getText(), txtFirstName.getText(), txtLastName.getText(), txtAddress.getText(), txtTelNo.getText(), txtNIC.getText());
            try {
                boolean result = OwnerController.addOwner(owner);

                if (result) {
                    JOptionPane.showMessageDialog(this, "Owner has been successfully added.");
                    isAdded();
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "Owner hasn't been added due to some error");
                }

            } catch (Exception ex) {
                Logger.getLogger(AddAppointmentPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAddOwnerMouseClicked

    private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMousePressed
        btnCancel.setBackground(new Color(200, 200, 200));
    }//GEN-LAST:event_btnCancelMousePressed

    private void btnCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseReleased
        btnCancel.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnCancelMouseReleased

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void txtNICFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNICFocusGained
        txtNIC.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtNICFocusGained

    private void txtNICFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNICFocusLost
        if (Validation.nicValidation(txtNIC)) {
            btnAddOwner.setEnabled(true);
        } else {
            btnAddOwner.setEnabled(false);
            txtNIC.setForeground(Color.red);
        }

    }//GEN-LAST:event_txtNICFocusLost

    private void txtTelNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelNoFocusGained
        txtTelNo.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtTelNoFocusGained

    private void txtTelNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelNoFocusLost
        if (Validation.phoneNumber(txtTelNo)) {
            btnAddOwner.setEnabled(true);
        } else {
            btnAddOwner.setEnabled(false);
            txtTelNo.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtTelNoFocusLost

    private void txtFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusGained
        txtFirstName.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtFirstNameFocusGained

    private void txtFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusLost
        if (Validation.name(txtFirstName)) {
            btnAddOwner.setEnabled(true);
        } else {
            btnAddOwner.setEnabled(false);
            txtFirstName.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtFirstNameFocusLost

    private void txtLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusGained
        txtLastName.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtLastNameFocusGained

    private void txtLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusLost
        if (Validation.name(txtLastName)) {
            btnAddOwner.setEnabled(true);
        } else {
            txtLastName.setForeground(Color.red);
            btnAddOwner.setEnabled(false);
        }
    }//GEN-LAST:event_txtLastNameFocusLost

    private void txtNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICActionPerformed
        txtTelNo.requestFocus();
    }//GEN-LAST:event_txtNICActionPerformed

    private void txtTelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelNoActionPerformed
       txtFirstName.requestFocus();
    }//GEN-LAST:event_txtTelNoActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        txtLastName.requestFocus();
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        txtAddress.requestFocus();
    }//GEN-LAST:event_txtLastNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogFormAddOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogFormAddOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogFormAddOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogFormAddOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogFormAddOwner dialog = new DialogFormAddOwner(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddOwner;
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txtAddress;
    private org.jdesktop.swingx.JXTextField txtFirstName;
    private org.jdesktop.swingx.JXTextField txtLastName;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtOwnerID;
    private javax.swing.JTextField txtTelNo;
    // End of variables declaration//GEN-END:variables

    public static boolean isAdded() {
        return true;
    }

    private void getOwnerID() {
        String newID;
        try {
            newID = IDGenarator.getNewID("owner", "OID", "O");
            txtOwnerID.setText(newID);
        } catch (SQLException ex) {
            Logger.getLogger(DialogFormAddOwner.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DialogFormAddOwner.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
