/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.animalclinic.view;

import java.awt.Color;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.animalclinic.common.IDGenarator;
import lk.ijse.animalclinic.common.Validation;
import lk.ijse.animalclinic.controller.SheduleController;
import lk.ijse.animalclinic.controller.VetController;
import lk.ijse.animalclinic.core.dto.SheduleDTO;
import lk.ijse.animalclinic.core.dto.VetDTO;
import lk.ijse.animalclinic.dao.custom.SheduleDAO;
import static lk.ijse.animalclinic.view.DialogFormAddPet.isAdded;
import lk.ijse.animalclinic.view.panels.VeterinaryPanel;

/**
 *
 * @author chamindu
 */
public class DialogFormAddShedule extends javax.swing.JDialog {

    /**
     * Creates new form DialogFormAddShedule
     */
    public DialogFormAddShedule(java.awt.Frame parent, boolean modal) {
        initComponents();
        getsheduleID();
        loadAllVetIDs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cmbDay = new org.jdesktop.swingx.JXComboBox();
        jLabel29 = new javax.swing.JLabel();
        cmbVetID = new org.jdesktop.swingx.JXComboBox();
        jLabel56 = new javax.swing.JLabel();
        txtVetFirstName1 = new org.jdesktop.swingx.JXTextField();
        txtVetLastName1 = new org.jdesktop.swingx.JXTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        txtSheduleID = new javax.swing.JTextField();
        btnAddShedule = new javax.swing.JLabel();
        btnCancel = new javax.swing.JLabel();
        txtInTime = new org.jdesktop.swingx.JXTextField();
        txtOutTime = new org.jdesktop.swingx.JXTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(250, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 135, 173), 5));
        jPanel1.setForeground(new java.awt.Color(40, 135, 173));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(40, 135, 173));
        jLabel31.setText("Shedule ID    -");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(40, 135, 173));
        jLabel30.setText("Day              -");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 110, 30));

        cmbDay.setBackground(new java.awt.Color(250, 255, 255));
        cmbDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SunDay", "MonDay", "TuesDay", "WednesDay", "ThursDay", "FriDay", "SaturDay" }));
        cmbDay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbDay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDayItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 240, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(40, 135, 173));
        jLabel29.setText("Vet.ID           -");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, 30));

        cmbVetID.setBackground(new java.awt.Color(250, 255, 255));
        cmbVetID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbVetID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVetIDItemStateChanged(evt);
            }
        });
        cmbVetID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVetIDActionPerformed(evt);
            }
        });
        jPanel1.add(cmbVetID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 220, 30));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(40, 135, 173));
        jLabel56.setText("Vet Name    -");
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 100, 30));

        txtVetFirstName1.setEditable(false);
        txtVetFirstName1.setBackground(new java.awt.Color(250, 255, 255));
        txtVetFirstName1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtVetFirstName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVetFirstName1.setPrompt("First Name");
        jPanel1.add(txtVetFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 240, 30));

        txtVetLastName1.setEditable(false);
        txtVetLastName1.setBackground(new java.awt.Color(250, 255, 255));
        txtVetLastName1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtVetLastName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVetLastName1.setPrompt("Last Name");
        jPanel1.add(txtVetLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 360, 30));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(40, 135, 173));
        jLabel48.setText("In Time       -");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 170, 100, 30));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(40, 135, 173));
        jLabel49.setText("Out Time     -");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 100, 30));

        jLabel55.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(29, 120, 156));
        jLabel55.setText("Add Shedule");
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 40));

        txtSheduleID.setEditable(false);
        txtSheduleID.setBackground(new java.awt.Color(250, 255, 255));
        txtSheduleID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtSheduleID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSheduleID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSheduleIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtSheduleID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 220, 30));

        btnAddShedule.setBackground(new java.awt.Color(102, 102, 102));
        btnAddShedule.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddShedule.setForeground(new java.awt.Color(255, 255, 255));
        btnAddShedule.setText("  + New Shedule");
        btnAddShedule.setOpaque(true);
        btnAddShedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddSheduleMouseClicked(evt);
            }
        });
        jPanel1.add(btnAddShedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 160, 50));

        btnCancel.setBackground(new java.awt.Color(102, 102, 102));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("       Cancel");
        btnCancel.setOpaque(true);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 290, 130, 50));

        txtInTime.setBackground(new java.awt.Color(250, 255, 255));
        txtInTime.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtInTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInTime.setPrompt("HH:MM");
        txtInTime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInTimeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInTimeFocusLost(evt);
            }
        });
        txtInTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInTimeActionPerformed(evt);
            }
        });
        jPanel1.add(txtInTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 240, 30));

        txtOutTime.setBackground(new java.awt.Color(250, 255, 255));
        txtOutTime.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtOutTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOutTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOutTime.setPrompt("HH:MM");
        jPanel1.add(txtOutTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1102, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDayItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDayItemStateChanged

    private void cmbVetIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVetIDItemStateChanged
        try {
            VetDTO vet = VetController.searchVetByID(cmbVetID.getSelectedItem().toString());
            txtVetFirstName1.setText(vet.getfName());
            txtVetLastName1.setText(vet.getlName());
        } catch (Exception ex) {
            Logger.getLogger(DialogFormAddShedule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbVetIDItemStateChanged

    private void txtSheduleIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSheduleIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSheduleIDActionPerformed

    private void btnAddSheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddSheduleMouseClicked
        SheduleDTO sDTO = new SheduleDTO(txtSheduleID.getText(), cmbVetID.getSelectedItem().toString(), cmbDay.getSelectedItem().toString(),txtInTime.getText(),txtOutTime.getText());
        try {
            boolean result = SheduleController.addShedule(sDTO);
            if (result) {
                JOptionPane.showMessageDialog(this, "Shedule has been successfully added.");
                isAdded();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Shedule hasn't been added due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(DialogFormAddShedule.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnAddSheduleMouseClicked

    private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMousePressed
        btnCancel.setBackground(new Color(200, 200, 200));
    }//GEN-LAST:event_btnCancelMousePressed

    private void btnCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseReleased
        btnCancel.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnCancelMouseReleased

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void txtInTimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInTimeFocusGained
       txtInTime.setForeground(Color.black);
    }//GEN-LAST:event_txtInTimeFocusGained

    private void txtInTimeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInTimeFocusLost
       if(Validation.time(txtInTime)){
           btnAddShedule.setEnabled(true);
       }else{
           txtInTime.setForeground(Color.red);
           btnAddShedule.setEnabled(false);
       }
    }//GEN-LAST:event_txtInTimeFocusLost

    private void cmbVetIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVetIDActionPerformed
        txtInTime.requestFocus();
    }//GEN-LAST:event_cmbVetIDActionPerformed

    private void txtInTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInTimeActionPerformed
        txtOutTime.requestFocus();
    }//GEN-LAST:event_txtInTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogFormAddShedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogFormAddShedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogFormAddShedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogFormAddShedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogFormAddShedule dialog = new DialogFormAddShedule(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddShedule;
    private javax.swing.JLabel btnCancel;
    private org.jdesktop.swingx.JXComboBox cmbDay;
    private org.jdesktop.swingx.JXComboBox cmbVetID;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXTextField txtInTime;
    private org.jdesktop.swingx.JXTextField txtOutTime;
    private javax.swing.JTextField txtSheduleID;
    private org.jdesktop.swingx.JXTextField txtVetFirstName1;
    private org.jdesktop.swingx.JXTextField txtVetLastName1;
    // End of variables declaration//GEN-END:variables
    public static boolean isAdded() {
        return true;
    }

    private void getsheduleID() {
        String newID;
        try {
            newID = IDGenarator.getNewID("shedule", "SID", "S");
            txtSheduleID.setText(newID);
        } catch (SQLException ex) {
            Logger.getLogger(DialogFormAddShedule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DialogFormAddShedule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllVetIDs() {
        try {
            ArrayList<VetDTO> allVet = VetController.getAllVets();
            cmbVetID.removeAllItems();
            if (allVet == null) {
                return;
            }
            for (VetDTO vet : allVet) {
                cmbVetID.addItem(vet.getVID());
            }
        } catch (Exception ex) {
            Logger.getLogger(DialogFormAddShedule.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
}
