/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.animalclinic.view;

import java.awt.Color;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.animalclinic.common.IDGenarator;
import lk.ijse.animalclinic.common.Validation;
import lk.ijse.animalclinic.controller.MedicineController;
import lk.ijse.animalclinic.core.dto.MedicineDTO;
import lk.ijse.animalclinic.view.panels.AddAppointmentPanel;

/**
 *
 * @author chamindu
 */
public class DialogFormAddMedicine extends javax.swing.JDialog {

    /**
     * Creates new form DialogFormAddMedicine
     */
    public DialogFormAddMedicine(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getMedicineID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtMedDesc = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtMID = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txtMedPrice = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        txtQtyOnHand = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        btnAddMedicine = new javax.swing.JLabel();
        btnCancel = new javax.swing.JLabel();
        cmbMedType = new org.jdesktop.swingx.JXComboBox();
        txtExpDate = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(250, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 135, 173), 5));
        jPanel1.setForeground(new java.awt.Color(40, 135, 173));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(40, 135, 173));
        jLabel42.setText(" Type                       -");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 30));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(40, 135, 173));
        jLabel43.setText(" Medicine desc.       -");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, 30));

        txtMedDesc.setBackground(new java.awt.Color(250, 255, 255));
        txtMedDesc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMedDesc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtMedDesc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMedDescFocusGained(evt);
            }
        });
        txtMedDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedDescActionPerformed(evt);
            }
        });
        jPanel1.add(txtMedDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 900, 30));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(40, 135, 173));
        jLabel44.setText(" Medicine ID            -");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 30));

        txtMID.setEditable(false);
        txtMID.setBackground(new java.awt.Color(250, 255, 255));
        txtMID.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtMID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtMID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 260, 30));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(40, 135, 173));
        jLabel45.setText(" Exp.Date                -");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 160, 30));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(40, 135, 173));
        jLabel46.setText(" Price                       -");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 160, 30));

        txtMedPrice.setBackground(new java.awt.Color(250, 255, 255));
        txtMedPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMedPrice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtMedPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMedPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMedPriceFocusLost(evt);
            }
        });
        txtMedPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtMedPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 260, 30));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(40, 135, 173));
        jLabel47.setText(" QtyOnHand           -");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 160, 30));

        txtQtyOnHand.setBackground(new java.awt.Color(250, 255, 255));
        txtQtyOnHand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtQtyOnHand.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQtyOnHand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQtyOnHandFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQtyOnHandFocusLost(evt);
            }
        });
        jPanel1.add(txtQtyOnHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 260, 30));

        jLabel41.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(29, 120, 156));
        jLabel41.setText("Add New Medicine ");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 40));

        btnAddMedicine.setBackground(new java.awt.Color(102, 102, 102));
        btnAddMedicine.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddMedicine.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMedicine.setText("+ New Medicine");
        btnAddMedicine.setOpaque(true);
        btnAddMedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMedicineMouseClicked(evt);
            }
        });
        jPanel1.add(btnAddMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 160, 50));

        btnCancel.setBackground(new java.awt.Color(102, 102, 102));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("       Cancel");
        btnCancel.setOpaque(true);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 350, 130, 50));

        cmbMedType.setBackground(new java.awt.Color(250, 255, 255));
        cmbMedType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Injection", "Lotion", "Tablet", "Other" }));
        cmbMedType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbMedType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMedTypeActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMedType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 260, 30));

        txtExpDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtExpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpDateActionPerformed(evt);
            }
        });
        jPanel1.add(txtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 260, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMedicineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMedicineMouseClicked
        if (txtExpDate.getDate() == null||txtMedDesc.getText().isEmpty()||txtMedPrice.getText().isEmpty()||txtQtyOnHand.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all");
        } else {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Date date = txtExpDate.getDate();
            MedicineDTO medicine = new MedicineDTO(txtMID.getText(), txtMedDesc.getText(), cmbMedType.getSelectedItem().toString(), df.format(date), Double.parseDouble(txtMedPrice.getText()), Integer.parseInt(txtQtyOnHand.getText()));
            try {
                boolean result = MedicineController.addMedicine(medicine);

                if (result) {
                    JOptionPane.showMessageDialog(this, "Medicine has been successfully added.");
                    isAdded();
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "Medicine hasn't been added due to some error");
                }
            } catch (Exception ex) {
                Logger.getLogger(DialogFormAddMedicine.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnAddMedicineMouseClicked

    private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMousePressed
        btnCancel.setBackground(new Color(200, 200, 200));
    }//GEN-LAST:event_btnCancelMousePressed

    private void btnCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseReleased
        btnCancel.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnCancelMouseReleased

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void cmbMedTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMedTypeActionPerformed
       txtExpDate.requestFocus();
    }//GEN-LAST:event_cmbMedTypeActionPerformed

    private void txtMedDescFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMedDescFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedDescFocusGained

    private void txtMedPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMedPriceFocusGained
        txtMedPrice.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtMedPriceFocusGained

    private void txtMedPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMedPriceFocusLost
        if (Validation.priceText(txtMedPrice)) {
            btnAddMedicine.setEnabled(true);
        } else {
            btnAddMedicine.setEnabled(false);
            txtMedPrice.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtMedPriceFocusLost

    private void txtQtyOnHandFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtyOnHandFocusGained
        txtQtyOnHand.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtQtyOnHandFocusGained

    private void txtQtyOnHandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtyOnHandFocusLost
        if (Validation.numberOnly(txtQtyOnHand)) {
            btnAddMedicine.setEnabled(true);
        } else {
            btnAddMedicine.setEnabled(false);
            txtQtyOnHand.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtQtyOnHandFocusLost

    private void txtMedDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedDescActionPerformed
       cmbMedType.requestFocus();
    }//GEN-LAST:event_txtMedDescActionPerformed

    private void txtExpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpDateActionPerformed
        txtMedPrice.requestFocus();
    }//GEN-LAST:event_txtExpDateActionPerformed

    private void txtMedPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedPriceActionPerformed
        txtQtyOnHand.requestFocus();
    }//GEN-LAST:event_txtMedPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogFormAddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogFormAddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogFormAddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogFormAddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogFormAddMedicine dialog = new DialogFormAddMedicine(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddMedicine;
    private javax.swing.JLabel btnCancel;
    private org.jdesktop.swingx.JXComboBox cmbMedType;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXDatePicker txtExpDate;
    private javax.swing.JTextField txtMID;
    private javax.swing.JTextField txtMedDesc;
    private javax.swing.JTextField txtMedPrice;
    private javax.swing.JTextField txtQtyOnHand;
    // End of variables declaration//GEN-END:variables
    public static boolean isAdded() {
        return true;
    }

    private void getMedicineID() {
        String newID;
        try {
            newID = IDGenarator.getNewID("medicine", "MID", "M");
            txtMID.setText(newID);
        } catch (SQLException ex) {
            Logger.getLogger(DialogFormAddMedicine.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DialogFormAddMedicine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
