/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.animalclinic.view;

import lk.ijse.animalclinic.view.panels.DashBoardPayment;
import lk.ijse.animalclinic.view.panels.DashBordPet;
import lk.ijse.animalclinic.view.panels.DashBoardVet;
import lk.ijse.animalclinic.view.panels.DashBoardAppointment;
import lk.ijse.animalclinic.view.panels.DashboardMedicine;
import lk.ijse.animalclinic.view.panels.MedicinePanel;
import lk.ijse.animalclinic.view.panels.VeterinaryPanel;
import lk.ijse.animalclinic.view.panels.AddAppointmentPanel;
import lk.ijse.animalclinic.view.panels.MakePayementPanel;
import lk.ijse.animalclinic.view.panels.AddPetTreatmentPanel;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import jdk.nashorn.internal.codegen.CompilerConstants;
import lk.ijse.animalclinic.view.panels.ReportPanel;
import lk.ijse.animalclinic.view.panels.ViewOwnerPanel;

/**
 *
 * @author chamindu
 */
public class HomeFrame extends javax.swing.JFrame {
    public static JFrame homeFrame;
    /**
     * Creates new form Home
     */
    public HomeFrame() {
        initComponents();
        homeFrame=this;
        
        setPanelColour(pnlApp);
        resetPanelColour(pnlPay, pnlPet, pnlVet, pnlMedicine, pnlReports);

        DashBoardAppointment dashBoard = new DashBoardAppointment();
        this.pnlDashBoard.removeAll();
        dashBoard.setSize(this.pnlDashBoard.getSize());
        pnlDashBoard.add(dashBoard);
        pnlDashBoard.revalidate();
        pnlDashBoard.repaint();

        AddAppointmentPanel appPanel = new AddAppointmentPanel();
        pnlMiddle.removeAll();
        appPanel.setSize(pnlMiddle.getSize());
        pnlMiddle.add(appPanel);
        pnlMiddle.revalidate();
        pnlMiddle.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblSettings = new javax.swing.JLabel();
        lblLogOut = new javax.swing.JLabel();
        pnlApp = new javax.swing.JPanel();
        pnlPet = new javax.swing.JPanel();
        pnlVet = new javax.swing.JPanel();
        pnlMedicine = new javax.swing.JPanel();
        pnlReports = new javax.swing.JPanel();
        lblApp = new javax.swing.JLabel();
        lblVet = new javax.swing.JLabel();
        lblMedicine = new javax.swing.JLabel();
        lblPay = new javax.swing.JLabel();
        lblReport = new javax.swing.JLabel();
        pnlDashBoard = new javax.swing.JLayeredPane();
        pnlMiddle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Border = new javax.swing.JLabel();
        pnlPay = new javax.swing.JPanel();
        lblPet = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel13MouseEntered(evt);
            }
        });
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 48)); // NOI18N
        jLabel30.setText("Dr.Vet");
        jPanel13.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 240, 70));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/animalclinic/images/logo.png"))); // NOI18N
        jPanel13.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 76));

        lblSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/animalclinic/images/settings (2).png"))); // NOI18N
        lblSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSettingsMouseExited(evt);
            }
        });
        jPanel13.add(lblSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 6, 70, 70));

        lblLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/animalclinic/images/logout (3).png"))); // NOI18N
        lblLogOut.setText("ADMIN");
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogOutMouseEntered(evt);
            }
        });
        jPanel13.add(lblLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 6, 110, 70));

        jPanel10.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1550, 80));

        javax.swing.GroupLayout pnlAppLayout = new javax.swing.GroupLayout(pnlApp);
        pnlApp.setLayout(pnlAppLayout);
        pnlAppLayout.setHorizontalGroup(
            pnlAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        pnlAppLayout.setVerticalGroup(
            pnlAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel10.add(pnlApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 240, 10));

        javax.swing.GroupLayout pnlPetLayout = new javax.swing.GroupLayout(pnlPet);
        pnlPet.setLayout(pnlPetLayout);
        pnlPetLayout.setHorizontalGroup(
            pnlPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        pnlPetLayout.setVerticalGroup(
            pnlPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel10.add(pnlPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 240, 10));

        javax.swing.GroupLayout pnlVetLayout = new javax.swing.GroupLayout(pnlVet);
        pnlVet.setLayout(pnlVetLayout);
        pnlVetLayout.setHorizontalGroup(
            pnlVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        pnlVetLayout.setVerticalGroup(
            pnlVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel10.add(pnlVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 240, 10));

        javax.swing.GroupLayout pnlMedicineLayout = new javax.swing.GroupLayout(pnlMedicine);
        pnlMedicine.setLayout(pnlMedicineLayout);
        pnlMedicineLayout.setHorizontalGroup(
            pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        pnlMedicineLayout.setVerticalGroup(
            pnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel10.add(pnlMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 210, 240, 10));

        javax.swing.GroupLayout pnlReportsLayout = new javax.swing.GroupLayout(pnlReports);
        pnlReports.setLayout(pnlReportsLayout);
        pnlReportsLayout.setHorizontalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        pnlReportsLayout.setVerticalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel10.add(pnlReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 210, 240, 10));

        lblApp.setBackground(new java.awt.Color(40, 135, 173));
        lblApp.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblApp.setForeground(new java.awt.Color(255, 255, 255));
        lblApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/animalclinic/images/pet (2).png"))); // NOI18N
        lblApp.setText("Appointment");
        lblApp.setOpaque(true);
        lblApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAppMouseEntered(evt);
            }
        });
        jPanel10.add(lblApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 240, 70));

        lblVet.setBackground(new java.awt.Color(40, 135, 173));
        lblVet.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblVet.setForeground(new java.awt.Color(255, 255, 255));
        lblVet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/animalclinic/images/veterinarian (1).png"))); // NOI18N
        lblVet.setText(" Veterinary");
        lblVet.setOpaque(true);
        lblVet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVetMouseEntered(evt);
            }
        });
        jPanel10.add(lblVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 240, 70));

        lblMedicine.setBackground(new java.awt.Color(40, 135, 173));
        lblMedicine.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblMedicine.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/animalclinic/images/medicine (3).png"))); // NOI18N
        lblMedicine.setText("Medicine");
        lblMedicine.setOpaque(true);
        lblMedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMedicineMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMedicineMouseClicked(evt);
            }
        });
        jPanel10.add(lblMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 130, 240, 70));

        lblPay.setBackground(new java.awt.Color(40, 135, 173));
        lblPay.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblPay.setForeground(new java.awt.Color(255, 255, 255));
        lblPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/animalclinic/images/get-money (1).png"))); // NOI18N
        lblPay.setText("  Payment");
        lblPay.setOpaque(true);
        lblPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPayMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPayMouseClicked(evt);
            }
        });
        jPanel10.add(lblPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 240, 70));

        lblReport.setBackground(new java.awt.Color(40, 135, 173));
        lblReport.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblReport.setForeground(new java.awt.Color(255, 255, 255));
        lblReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/animalclinic/images/report.png"))); // NOI18N
        lblReport.setText(" Reports");
        lblReport.setOpaque(true);
        lblReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportMouseEntered(evt);
            }
        });
        jPanel10.add(lblReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 130, 240, 70));

        pnlDashBoard.setOpaque(true);
        pnlDashBoard.setLayout(new java.awt.CardLayout());
        jPanel10.add(pnlDashBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 240, 720));

        pnlMiddle.setBackground(new java.awt.Color(255, 255, 255));
        pnlMiddle.setForeground(new java.awt.Color(255, 255, 255));
        pnlMiddle.setLayout(new java.awt.CardLayout());
        jPanel10.add(pnlMiddle, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 1280, 720));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/animalclinic/images/x-mark (3).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 5, 32, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/animalclinic/images/minimize.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 5, 32, 32));

        Border.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 135, 173), 2, true));
        jPanel10.add(Border, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 970));

        javax.swing.GroupLayout pnlPayLayout = new javax.swing.GroupLayout(pnlPay);
        pnlPay.setLayout(pnlPayLayout);
        pnlPayLayout.setHorizontalGroup(
            pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        pnlPayLayout.setVerticalGroup(
            pnlPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel10.add(pnlPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 240, 10));

        lblPet.setBackground(new java.awt.Color(40, 135, 173));
        lblPet.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblPet.setForeground(new java.awt.Color(255, 255, 255));
        lblPet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/animalclinic/images/pawprint (4).png"))); // NOI18N
        lblPet.setText("   Pet");
        lblPet.setOpaque(true);
        lblPet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPetMouseEntered(evt);
            }
        });
        jPanel10.add(lblPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 240, 70));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 970));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAppMouseClicked
        setPanelColour(pnlApp);
        resetPanelColour(pnlPay, pnlPet, pnlVet, pnlMedicine, pnlReports);
                
        
        
        
        DashBoardAppointment dashBoard = new DashBoardAppointment();
        this.pnlDashBoard.removeAll();
        dashBoard.setSize(this.pnlDashBoard.getSize());
        pnlDashBoard.add(dashBoard);
        pnlDashBoard.revalidate();
        pnlDashBoard.repaint();

        AddAppointmentPanel appPanel = new AddAppointmentPanel();
        pnlMiddle.removeAll();
        appPanel.setSize(pnlMiddle.getSize());
        pnlMiddle.add(appPanel);
        pnlMiddle.revalidate();
        pnlMiddle.repaint();

    }//GEN-LAST:event_lblAppMouseClicked

    private void lblAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAppMouseEntered
        lblApp.setBackground(new Color(69, 108, 123));

    }//GEN-LAST:event_lblAppMouseEntered

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered
        resetLabelColour(lblApp);
        resetLabelColour(lblPay);
        resetLabelColour(lblPet);
        resetLabelColour(lblVet);
        resetLabelColour(lblMedicine);
        resetLabelColour(lblReport);
    }//GEN-LAST:event_jPanel10MouseEntered

    private void lblPayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPayMouseEntered
        setLabelColour(lblPay);
    }//GEN-LAST:event_lblPayMouseEntered

    private void lblPetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPetMouseEntered
        setLabelColour(lblPet);
    }//GEN-LAST:event_lblPetMouseEntered

    private void lblVetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVetMouseEntered
        setLabelColour(lblVet);
    }//GEN-LAST:event_lblVetMouseEntered

    private void lblMedicineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMedicineMouseEntered
        setLabelColour(lblMedicine);
    }//GEN-LAST:event_lblMedicineMouseEntered

    private void lblPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPayMouseClicked
        setPanelColour(pnlPay);
        resetPanelColour(pnlApp, pnlPet, pnlVet, pnlMedicine, pnlReports);

        DashBoardPayment dashBoard = new DashBoardPayment();
        this.pnlDashBoard.removeAll();
        dashBoard.setSize(this.pnlDashBoard.getSize());
        pnlDashBoard.add(dashBoard);
        pnlDashBoard.revalidate();
        pnlDashBoard.repaint();

        AddPetTreatmentPanel treatment= new AddPetTreatmentPanel();
        pnlMiddle.removeAll();
        treatment.setSize(pnlMiddle.getSize());
        pnlMiddle.add(treatment);
        pnlMiddle.revalidate();
        pnlMiddle.repaint();

    }//GEN-LAST:event_lblPayMouseClicked

    private void lblPetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPetMouseClicked
        setPanelColour(pnlPet);
        resetPanelColour(pnlApp, pnlPay, pnlVet, pnlMedicine, pnlReports);

        DashBordPet dashBoard = new DashBordPet();
        this.pnlDashBoard.removeAll();
        dashBoard.setSize(this.pnlDashBoard.getSize());
        pnlDashBoard.add(dashBoard);
        pnlDashBoard.revalidate();
        pnlDashBoard.repaint();

        ViewOwnerPanel owner = new ViewOwnerPanel();
        pnlMiddle.removeAll();
        owner.setSize(pnlMiddle.getSize());
        pnlMiddle.add(owner);
        pnlMiddle.revalidate();
        pnlMiddle.repaint();
    }//GEN-LAST:event_lblPetMouseClicked

    private void lblVetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVetMouseClicked
        setPanelColour(pnlVet);
        resetPanelColour(pnlApp, pnlPay, pnlPet, pnlMedicine, pnlReports);

        DashBoardVet dashBoard = new DashBoardVet();
        this.pnlDashBoard.removeAll();
        dashBoard.setSize(this.pnlDashBoard.getSize());
        pnlDashBoard.add(dashBoard);
        pnlDashBoard.revalidate();
        pnlDashBoard.repaint();

        VeterinaryPanel vet = new VeterinaryPanel();
        pnlMiddle.removeAll();
        vet.setSize(pnlMiddle.getSize());
        pnlMiddle.add(vet);
        pnlMiddle.revalidate();
        pnlMiddle.repaint();
    }//GEN-LAST:event_lblVetMouseClicked

    private void lblMedicineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMedicineMouseClicked
        setPanelColour(pnlMedicine);
        resetPanelColour(pnlApp, pnlPay, pnlPet, pnlVet, pnlReports);
        
        DashboardMedicine dashBoard = new DashboardMedicine();
        this.pnlDashBoard.removeAll();
        dashBoard.setSize(this.pnlDashBoard.getSize());
        pnlDashBoard.add(dashBoard);
        pnlDashBoard.revalidate();
        pnlDashBoard.repaint();

        MedicinePanel medicine = new MedicinePanel();
        pnlMiddle.removeAll();
        medicine.setSize(pnlMiddle.getSize());
        pnlMiddle.add(medicine);
        pnlMiddle.revalidate();
        pnlMiddle.repaint();

    }//GEN-LAST:event_lblMedicineMouseClicked

    private void lblReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseEntered
        lblReport.setBackground(new Color(69, 108, 123));
    }//GEN-LAST:event_lblReportMouseEntered

    private void lblReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseClicked
        setPanelColour(pnlReports);
        resetPanelColour(pnlApp, pnlPay, pnlPet, pnlVet, pnlMedicine);
        ReportPanel rPanel = new ReportPanel();
        pnlMiddle.removeAll();
        rPanel.setSize(pnlMiddle.getSize());
        pnlMiddle.add(rPanel);
        pnlMiddle.revalidate();
        pnlMiddle.repaint();
    }//GEN-LAST:event_lblReportMouseClicked

    private void lblSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseEntered
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/animalclinic/images/settings (COLOR).png"));
        lblSettings.setIcon(icon);
    }//GEN-LAST:event_lblSettingsMouseEntered

    private void lblSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseClicked
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/animalclinic/images/settings (COLOR).png"));
        lblSettings.setIcon(icon);
    }//GEN-LAST:event_lblSettingsMouseClicked

    private void jPanel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseEntered
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/animalclinic/images/logout (3).png"));
        lblLogOut.setIcon(icon);
        ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/lk/ijse/animalclinic/images/settings (2).png"));
        lblSettings.setIcon(icon1);

    }//GEN-LAST:event_jPanel13MouseEntered

    private void lblLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseEntered
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/animalclinic/images/logout (4).png"));
        lblLogOut.setIcon(icon);
    }//GEN-LAST:event_lblLogOutMouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(1);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
        this.dispose();
        Login login= new Login();
        login.setVisible(true);
    }//GEN-LAST:event_lblLogOutMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        setExtendedState(HomeFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void lblSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSettingsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Border;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblApp;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblMedicine;
    private javax.swing.JLabel lblPay;
    private javax.swing.JLabel lblPet;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblSettings;
    private javax.swing.JLabel lblVet;
    private javax.swing.JPanel pnlApp;
    private javax.swing.JLayeredPane pnlDashBoard;
    private javax.swing.JPanel pnlMedicine;
    private static javax.swing.JPanel pnlMiddle;
    private javax.swing.JPanel pnlPay;
    private javax.swing.JPanel pnlPet;
    private javax.swing.JPanel pnlReports;
    private javax.swing.JPanel pnlVet;
    // End of variables declaration//GEN-END:variables
     private void setPanelColour(JPanel panel) {
        panel.setBackground(new Color(40,135,173));
    }

    private void resetPanelColour(JPanel pnl1, JPanel pnl2, JPanel pnl3, JPanel pnl4, JPanel pnl5) {
        pnl1.setBackground(new Color(240, 240, 240));
        pnl2.setBackground(new Color(240, 240, 240));
        pnl3.setBackground(new Color(240, 240, 240));
        pnl4.setBackground(new Color(240, 240, 240));
        pnl5.setBackground(new Color(240, 240, 240));
    }

    private void setLabelColour(JLabel Label) {
        Label.setBackground(new Color(69, 108, 123));
    }

    private void resetLabelColour(JLabel Label) {
        Label.setBackground(new Color(40, 135, 173));
    }

    public static JPanel getMiddlePanel() {
        return pnlMiddle;
    }
    
}
