/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.animalclinic.view.panels;

import lk.ijse.animalclinic.view.panels.AddAppointmentPanel;
import lk.ijse.animalclinic.view.panels.ViewAppointmentPanel;
import java.awt.Color;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import lk.ijse.animalclinic.view.HomeFrame;

/**
 *
 * @author chamindu
 */
public class DashBoardAppointment extends javax.swing.JPanel {

    /**
     * Creates new form AppointmentDashBoard
     */
    public DashBoardAppointment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel25 = new javax.swing.JPanel();
        lblAddApp = new javax.swing.JLabel();
        lblViewApp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel25.setBackground(new java.awt.Color(42, 42, 42));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddApp.setBackground(new java.awt.Color(40, 135, 173));
        lblAddApp.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblAddApp.setForeground(new java.awt.Color(204, 204, 204));
        lblAddApp.setText("   Add Appointment");
        lblAddApp.setOpaque(true);
        lblAddApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddAppMouseClicked(evt);
            }
        });
        jPanel25.add(lblAddApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 70));

        lblViewApp.setBackground(new java.awt.Color(42, 42, 42));
        lblViewApp.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        lblViewApp.setForeground(new java.awt.Color(204, 204, 204));
        lblViewApp.setText("   View Appointment");
        lblViewApp.setOpaque(true);
        lblViewApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewAppMouseClicked(evt);
            }
        });
        jPanel25.add(lblViewApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/animalclinic/images/dog-in-front-of-a-man (1).png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel25.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 140, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblAddAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddAppMouseClicked
        lblViewApp.setBackground(new Color(42, 42, 42));
        lblAddApp.setBackground(new Color(40, 135, 173));
        AddAppointmentPanel appPanel = new AddAppointmentPanel();
        JPanel middlePanel = HomeFrame.getMiddlePanel();
        middlePanel.removeAll();
        appPanel.setSize(middlePanel.getSize());
        middlePanel.add(appPanel);
        middlePanel.revalidate();
        middlePanel.repaint();

    }//GEN-LAST:event_lblAddAppMouseClicked

    private void lblViewAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewAppMouseClicked
        lblAddApp.setBackground(new Color(42, 42, 42));
        lblViewApp.setBackground(new Color(40, 135, 173));
        ViewAppointmentPanel viewPanel = new ViewAppointmentPanel();
        JPanel middlePanel=HomeFrame.getMiddlePanel();
        middlePanel.removeAll();
        viewPanel.setSize(middlePanel.getSize());
        middlePanel.add(viewPanel);
        middlePanel.revalidate();
        middlePanel.repaint();
        
    }//GEN-LAST:event_lblViewAppMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JLabel lblAddApp;
    private javax.swing.JLabel lblViewApp;
    // End of variables declaration//GEN-END:variables
}
