/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.animalclinic.view.panels;

/**
 *
 * @author chamindu
 */
public class DashboardMedicine extends javax.swing.JPanel {

    /**
     * Creates new form AddMedicinePanel
     */
    public DashboardMedicine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel33 = new javax.swing.JPanel();
        lblMakePayment = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel33.setBackground(new java.awt.Color(42, 42, 42));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMakePayment.setBackground(new java.awt.Color(40, 135, 173));
        lblMakePayment.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblMakePayment.setForeground(new java.awt.Color(204, 204, 204));
        lblMakePayment.setText("   View Medicine");
        lblMakePayment.setOpaque(true);
        lblMakePayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMakePaymentMouseClicked(evt);
            }
        });
        jPanel33.add(lblMakePayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/animalclinic/images/syringe (1).png"))); // NOI18N
        jPanel33.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 140, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblMakePaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMakePaymentMouseClicked
        
    }//GEN-LAST:event_lblMakePaymentMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JLabel lblMakePayment;
    // End of variables declaration//GEN-END:variables
}
