/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.animalclinic.view.panels;

import lk.ijse.animalclinic.view.panels.ViewPetTreatmentPanel;
import lk.ijse.animalclinic.view.panels.ViewPetPanel;
import lk.ijse.animalclinic.view.panels.AddPetTreatmentPanel;
import lk.ijse.animalclinic.view.panels.ViewOwnerPanel;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import lk.ijse.animalclinic.view.HomeFrame;

/**
 *
 * @author chamindu
 */
public class DashBordPet extends javax.swing.JPanel {

    /**
     * Creates new form PetDashBord
     */
    public DashBordPet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel33 = new javax.swing.JPanel();
        lblViewPet = new javax.swing.JLabel();
        lblViewTreatment = new javax.swing.JLabel();
        lblViewOwner = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel33.setBackground(new java.awt.Color(42, 42, 42));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewPet.setBackground(new java.awt.Color(42, 42, 42));
        lblViewPet.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        lblViewPet.setForeground(new java.awt.Color(204, 204, 204));
        lblViewPet.setText("   View Pet  Details");
        lblViewPet.setOpaque(true);
        lblViewPet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewPetMouseClicked(evt);
            }
        });
        jPanel33.add(lblViewPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 70));

        lblViewTreatment.setBackground(new java.awt.Color(42, 42, 42));
        lblViewTreatment.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        lblViewTreatment.setForeground(new java.awt.Color(204, 204, 204));
        lblViewTreatment.setText("   View Pet Treatment");
        lblViewTreatment.setOpaque(true);
        lblViewTreatment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewTreatmentMouseClicked(evt);
            }
        });
        jPanel33.add(lblViewTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 240, 70));

        lblViewOwner.setBackground(new java.awt.Color(40, 135, 173));
        lblViewOwner.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        lblViewOwner.setForeground(new java.awt.Color(204, 204, 204));
        lblViewOwner.setText("   View Owner Details");
        lblViewOwner.setOpaque(true);
        lblViewOwner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewOwnerMouseClicked(evt);
            }
        });
        jPanel33.add(lblViewOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/animalclinic/images/Pet Label.png"))); // NOI18N
        jPanel33.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 140, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblViewTreatmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewTreatmentMouseClicked
        setLabelBackGround (lblViewOwner,lblViewPet,lblViewTreatment);
        ViewPetTreatmentPanel viewTreatmentPanel = new ViewPetTreatmentPanel();
        JPanel middlePanel = HomeFrame.getMiddlePanel();
        middlePanel.removeAll();
        viewTreatmentPanel.setSize(middlePanel.getSize());
        middlePanel.add(viewTreatmentPanel);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_lblViewTreatmentMouseClicked

    private void lblViewOwnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewOwnerMouseClicked
        setLabelBackGround (lblViewPet,lblViewTreatment,lblViewOwner);
        ViewOwnerPanel addPetPanel = new ViewOwnerPanel();
        JPanel middlePanel = HomeFrame.getMiddlePanel();
        middlePanel.removeAll();
        addPetPanel.setSize(middlePanel.getSize());
        middlePanel.add(addPetPanel);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_lblViewOwnerMouseClicked

    private void lblViewPetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPetMouseClicked
       setLabelBackGround (lblViewTreatment,lblViewOwner,lblViewPet);
        ViewPetPanel viewPetPanel = new ViewPetPanel();
        JPanel middlePanel = HomeFrame.getMiddlePanel();
        middlePanel.removeAll();
        viewPetPanel.setSize(middlePanel.getSize());
        middlePanel.add(viewPetPanel);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_lblViewPetMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JLabel lblViewOwner;
    private javax.swing.JLabel lblViewPet;
    private javax.swing.JLabel lblViewTreatment;
    // End of variables declaration//GEN-END:variables
public void setLabelBackGround(JLabel lbl1,JLabel lbl2,JLabel lblSelected){
    lbl1.setBackground(new Color(42, 42, 42));
    lbl2.setBackground(new Color(42, 42, 42));
    lblSelected.setBackground(new Color(40, 135, 173));
}
}
