/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.animalclinic.view.panels;

import java.awt.Color;
import javax.swing.JPanel;
import lk.ijse.animalclinic.view.HomeFrame;

/**
 *
 * @author chamindu
 */
public class DashBoardVet extends javax.swing.JPanel {

    /**
     * Creates new form VetDashBoard
     */
    public DashBoardVet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel33 = new javax.swing.JPanel();
        lblViewShedule = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblViewVeterinary = new javax.swing.JLabel();

        jPanel33.setBackground(new java.awt.Color(42, 42, 42));
        jPanel33.setPreferredSize(new java.awt.Dimension(240, 60));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewShedule.setBackground(new java.awt.Color(42, 42, 42));
        lblViewShedule.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        lblViewShedule.setForeground(new java.awt.Color(204, 204, 204));
        lblViewShedule.setText("   View  Schedule");
        lblViewShedule.setOpaque(true);
        lblViewShedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewSheduleMouseClicked(evt);
            }
        });
        jPanel33.add(lblViewShedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/animalclinic/images/veterinarian-hospital.png"))); // NOI18N
        jPanel33.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 140, 420));

        lblViewVeterinary.setBackground(new java.awt.Color(40, 135, 173));
        lblViewVeterinary.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        lblViewVeterinary.setForeground(new java.awt.Color(204, 204, 204));
        lblViewVeterinary.setText("   View Veterinary");
        lblViewVeterinary.setOpaque(true);
        lblViewVeterinary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewVeterinaryMouseClicked(evt);
            }
        });
        jPanel33.add(lblViewVeterinary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblViewSheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewSheduleMouseClicked
        lblViewVeterinary.setBackground(new Color(42, 42, 42));
        lblViewShedule.setBackground(new Color(40, 135, 173));
        SchedulePanel viewPanel=new SchedulePanel();
        JPanel middlePanel = HomeFrame.getMiddlePanel();
        middlePanel.removeAll();
        viewPanel.setSize(middlePanel.getSize());
        middlePanel.add(viewPanel);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_lblViewSheduleMouseClicked

    private void lblViewVeterinaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewVeterinaryMouseClicked
        lblViewShedule.setBackground(new Color(42, 42, 42));
        lblViewVeterinary.setBackground(new Color(40, 135, 173));
        VeterinaryPanel viewPanel=new VeterinaryPanel();
        JPanel middlePanel = HomeFrame.getMiddlePanel();
        middlePanel.removeAll();
        viewPanel.setSize(middlePanel.getSize());
        middlePanel.add(viewPanel);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_lblViewVeterinaryMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JLabel lblViewShedule;
    private javax.swing.JLabel lblViewVeterinary;
    // End of variables declaration//GEN-END:variables
}
