/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.animalclinic.view.panels;

import java.awt.Dialog;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.animalclinic.controller.MedicineController;
import lk.ijse.animalclinic.controller.OwnerController;
import lk.ijse.animalclinic.core.dto.MedicineDTO;
import lk.ijse.animalclinic.core.dto.OwnerDTO;
import lk.ijse.animalclinic.dao.db.DBConnection;
import lk.ijse.jasper.IJSEJasperViewer;
import lk.ijse.jasper.JasperUtil;
import lk.ijse.jasper.Report;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperReportsContext;

/**
 *
 * @author chamindu
 */
@Report("lk.ijse.animalclinic.reports")
public class ReportPanel extends javax.swing.JPanel {

    private String id;

    /**
     * Creates new form ReportPanel
     */
    public ReportPanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnViewPet = new javax.swing.JButton();
        btnOwner = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnMedicine = new javax.swing.JButton();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        btnExpire = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnOwner1 = new javax.swing.JButton();
        btnOwner4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        btnOwner2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        btnOwner3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Owner NIC");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 120, 60));

        btnViewPet.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnViewPet.setText("Get Pet Details");
        btnViewPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPetActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 180, 70));

        btnOwner.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnOwner.setText("Get Owner Report");
        btnOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOwnerActionPerformed(evt);
            }
        });
        jPanel1.add(btnOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 180, 70));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 32, 340, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 32, 600, 300));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMedicine.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnMedicine.setText("View All Medicines");
        btnMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicineActionPerformed(evt);
            }
        });
        jPanel2.add(btnMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 180, 70));
        jPanel2.add(datePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 32, 210, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Date");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 40));

        btnExpire.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnExpire.setText("Search Expire Items ");
        jPanel2.add(btnExpire, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 180, 70));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 600, 300));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Payment ID");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 120, 60));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 32, 340, 40));

        btnOwner1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnOwner1.setText("Get treatment Details");
        btnOwner1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOwner1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnOwner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 180, 70));

        btnOwner4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnOwner4.setText("Get Payment Details");
        btnOwner4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOwner4ActionPerformed(evt);
            }
        });
        jPanel3.add(btnOwner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 180, 70));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 600, 300));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Veterinary NIC");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 120, 60));
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 32, 350, 40));

        btnOwner2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnOwner2.setText("Get All Veterinary");
        btnOwner2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOwner2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnOwner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 180, 70));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Veterinary tel.NO");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 60));
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 350, 40));

        btnOwner3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOwner3.setText("Get Veterinary Shedule");
        btnOwner3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOwner3ActionPerformed(evt);
            }
        });
        jPanel4.add(btnOwner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 180, 70));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 600, 300));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPetActionPerformed
       /* JasperUtil.init(MakePayementPanel.class);

        JasperReportsContext ctx = JasperUtil.getReportContext();

        try {
            JasperReport compiledReport = JasperUtil.getCompiledReport("Pet.jasper");

            JasperFillManager fillManager = JasperFillManager.getInstance(ctx);

            HashMap<String, Object> reportParams = new HashMap<>();
            reportParams.put("ownerID", cmbOwnerID.getSelectedItem().toString());
            Connection conn = DBConnection.getInstance().getConnection();
            JasperPrint filledReport = fillManager.
                    fill(compiledReport, reportParams, conn);

            IJSEJasperViewer frmJasperViewer = new IJSEJasperViewer(filledReport);
            frmJasperViewer.setTitle("My Report");
            frmJasperViewer.setSize(1600, 720);
            frmJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            frmJasperViewer.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(MakePayementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btnViewPetActionPerformed

    private void btnMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicineActionPerformed
        
    }//GEN-LAST:event_btnMedicineActionPerformed

    private void btnOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOwnerActionPerformed
        /*JasperUtil.init(MakePayementPanel.class);

        JasperReportsContext ctx = JasperUtil.getReportContext();
        
        try {
            JasperReport compiledReport = JasperUtil.getCompiledReport("Owner.jasper");

            JasperFillManager fillManager = JasperFillManager.getInstance(ctx);

            HashMap<String, Object> reportParams = new HashMap<>();
            reportParams.put("ownerID", cmbOwnerID.getSelectedItem().toString());
            Connection conn = DBConnection.getInstance().getConnection();
            JasperPrint filledReport = fillManager.
                    fill(compiledReport, reportParams, conn);

            IJSEJasperViewer frmJasperViewer = new IJSEJasperViewer(filledReport);
            frmJasperViewer.setTitle("My Report");
            frmJasperViewer.setSize(1600, 720);
            frmJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            frmJasperViewer.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(MakePayementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btnOwnerActionPerformed

    private void btnOwner1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOwner1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOwner1ActionPerformed

    private void btnOwner2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOwner2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOwner2ActionPerformed

    private void btnOwner3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOwner3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOwner3ActionPerformed

    private void btnOwner4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOwner4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOwner4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExpire;
    private javax.swing.JButton btnMedicine;
    private javax.swing.JButton btnOwner;
    private javax.swing.JButton btnOwner1;
    private javax.swing.JButton btnOwner2;
    private javax.swing.JButton btnOwner3;
    private javax.swing.JButton btnOwner4;
    private javax.swing.JButton btnViewPet;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables


   
}
