/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.animalclinic.view.panels;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.animalclinic.controller.OwnerController;
import lk.ijse.animalclinic.controller.VetController;
import lk.ijse.animalclinic.core.dto.OwnerDTO;
import lk.ijse.animalclinic.core.dto.VetDTO;
import lk.ijse.animalclinic.view.DialogFormAddOwner;
import lk.ijse.animalclinic.view.DialogFormAddVet;
import lk.ijse.animalclinic.view.HomeFrame;

/**
 *
 * @author chamindu
 */
public class VeterinaryPanel extends javax.swing.JPanel {

    /**
     * Creates new form VeterinaryPanel
     */
    public VeterinaryPanel() {
        initComponents();
        loadAllVetIDs();
        loadAllVeterinarians();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        txtTelNo = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        btnAddNew = new javax.swing.JLabel();
        btnRemoveVet = new javax.swing.JLabel();
        btnEditVet = new javax.swing.JLabel();
        txtFirstName = new org.jdesktop.swingx.JXTextField();
        txtLastName = new org.jdesktop.swingx.JXTextField();
        cmbVetID = new org.jdesktop.swingx.JXComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVetData = new org.jdesktop.swingx.JXTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setText("Tel.No        -");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 110, 30));

        txtDescription.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 1150, 30));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel55.setText("Vet Name  -");
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 110, 30));

        txtTelNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 240, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Vet.ID        -");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel59.setText("Description-");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 30));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel60.setText("Address     -");
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, 30));

        txtAddress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 1150, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("NIC            -");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 30));

        txtNIC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 240, 30));

        btnAddNew.setBackground(new java.awt.Color(204, 204, 204));
        btnAddNew.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddNew.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/animalclinic/images/add.png"))); // NOI18N
        btnAddNew.setText(" New Veterinary");
        btnAddNew.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAddNew.setOpaque(true);
        btnAddNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNewMouseClicked(evt);
            }
        });
        jPanel1.add(btnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 190, 50));

        btnRemoveVet.setBackground(new java.awt.Color(102, 102, 102));
        btnRemoveVet.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRemoveVet.setForeground(new java.awt.Color(189, 103, 107));
        btnRemoveVet.setText("  Remove");
        btnRemoveVet.setOpaque(true);
        btnRemoveVet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveVetMouseClicked(evt);
            }
        });
        jPanel1.add(btnRemoveVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 340, 130, 50));

        btnEditVet.setBackground(new java.awt.Color(102, 102, 102));
        btnEditVet.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnEditVet.setForeground(new java.awt.Color(255, 255, 255));
        btnEditVet.setText("      Edit");
        btnEditVet.setOpaque(true);
        btnEditVet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditVetMouseClicked(evt);
            }
        });
        jPanel1.add(btnEditVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 340, 130, 50));

        txtFirstName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtFirstName.setPrompt("First Name");
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 240, 30));

        txtLastName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtLastName.setPrompt("Last Name");
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 470, 30));

        cmbVetID.setBackground(new java.awt.Color(250, 255, 255));
        cmbVetID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVetIDItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbVetID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 240, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 1280, 390));

        tblVetData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vet ID", "First Name", "Last Name", "NIC", "Tel.No", "Address", "Description"
            }
        ));
        tblVetData.setEditable(false);
        tblVetData.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tblVetData.setRowHeight(25);
        tblVetData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVetDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVetData);
        if (tblVetData.getColumnModel().getColumnCount() > 0) {
            tblVetData.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblVetData.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblVetData.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblVetData.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblVetData.getColumnModel().getColumn(4).setPreferredWidth(10);
            tblVetData.getColumnModel().getColumn(5).setPreferredWidth(150);
            tblVetData.getColumnModel().getColumn(6).setPreferredWidth(200);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 320));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelNoActionPerformed

    private void btnAddNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMouseClicked
        DialogFormAddVet addVet = new DialogFormAddVet(HomeFrame.homeFrame, true);
        addVet.setVisible(true);
        if (DialogFormAddVet.isAdded()) {
            loadAllVetIDs();
            loadAllVeterinarians();
        }
    }//GEN-LAST:event_btnAddNewMouseClicked

    private void cmbVetIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVetIDItemStateChanged
        try {
            if (cmbVetID.getSelectedIndex() == -1) return;
            VetDTO vet = VetController.searchVetByID(cmbVetID.getSelectedItem().toString());
            if (vet == null) return;
            txtFirstName.setText(vet.getfName());
            txtLastName.setText(vet.getlName());
            txtNIC.setText(vet.getNIC());
            txtAddress.setText(vet.getAddress());
            txtTelNo.setText(vet.getTel());
            txtDescription.setText(vet.getDescription());
        } catch (Exception ex) {
            Logger.getLogger(VeterinaryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtNIC.requestFocus();
    }//GEN-LAST:event_cmbVetIDItemStateChanged

    private void btnEditVetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditVetMouseClicked
        VetDTO vet = new VetDTO(cmbVetID.getSelectedItem().toString(), txtFirstName.getText(), txtLastName.getText(), txtNIC.getText(), txtAddress.getText(), txtTelNo.getText(), txtDescription.getText());
        try {
            boolean result = VetController.editVet(vet);

            if (result) {
                JOptionPane.showMessageDialog(this, "Vet has been successfully Edited.");
                loadAllVeterinarians();
            } else {
                JOptionPane.showMessageDialog(this, "Vet hasn't been edited due to some error");
            }

        } catch (Exception ex) {
            Logger.getLogger(VeterinaryPanel.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btnEditVetMouseClicked

    private void btnRemoveVetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveVetMouseClicked
        VetDTO vet = new VetDTO(cmbVetID.getSelectedItem().toString(), txtFirstName.getText(), txtLastName.getText(), txtNIC.getText(), txtAddress.getText(), txtTelNo.getText(), txtDescription.getText());
        try {
            boolean result =VetController.removeVet(vet);
            if (result) {
                JOptionPane.showMessageDialog(this, "Veterinary has been successfully Removed.");
                txtAddress.setText(null);
                txtNIC.setText(null);
                txtDescription.setText(null);
                txtFirstName.setText(null);
                txtLastName.setText(null);
                txtTelNo.setText(null);
            } else {
                JOptionPane.showMessageDialog(this, "Veterinary hasn't been Removed due to some error");
            }

        } catch (Exception ex) {
            Logger.getLogger(MedicinePanel.class.getName()).log(Level.SEVERE, null, ex);
        } 
        loadAllVeterinarians();
    }//GEN-LAST:event_btnRemoveVetMouseClicked

    private void tblVetDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVetDataMouseClicked
        String id=(String) tblVetData.getValueAt(tblVetData.getSelectedRow(),0);
        try {
            if (tblVetData.getRowCount()==0) return;
            VetDTO vet = VetController.searchVetByID(id);
            if (vet == null) return;
            cmbVetID.setSelectedItem(vet.getVID());
            txtFirstName.setText(vet.getfName());
            txtLastName.setText(vet.getlName());
            txtNIC.setText(vet.getNIC());
            txtAddress.setText(vet.getAddress());
            txtTelNo.setText(vet.getTel());
            txtDescription.setText(vet.getDescription());
        } catch (Exception ex) {
            Logger.getLogger(VeterinaryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblVetDataMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddNew;
    private javax.swing.JLabel btnEditVet;
    private javax.swing.JLabel btnRemoveVet;
    private org.jdesktop.swingx.JXComboBox cmbVetID;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTable tblVetData;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDescription;
    private org.jdesktop.swingx.JXTextField txtFirstName;
    private org.jdesktop.swingx.JXTextField txtLastName;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtTelNo;
    // End of variables declaration//GEN-END:variables

    private void loadAllVetIDs() {

        try {
            ArrayList<VetDTO> allVet = VetController.getAllVets();
            cmbVetID.removeAllItems();
            if (allVet == null) {
                return;
            }
            for (VetDTO vet : allVet) {
                cmbVetID.addItem(vet.getVID());
            }
        } catch (Exception ex) {
            Logger.getLogger(VeterinaryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void loadAllVeterinarians() {
        try {
            ArrayList<VetDTO> allVet =VetController.getAllVets();

            DefaultTableModel dtm = (DefaultTableModel)tblVetData.getModel();
            dtm.setRowCount(0);

            if (allVet != null) {

                for (VetDTO vet : allVet) {

                    Object[] rowData = {
                        vet.getVID(),
                        vet.getfName(),
                        vet.getlName(),
                        vet.getNIC(),
                        vet.getTel(),
                        vet.getAddress(),
                        vet.getDescription()
                    };

                    dtm.addRow(rowData);

                }

            }

        } catch (Exception ex) {
            Logger.getLogger(VeterinaryPanel.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
}
