/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.animalclinic.view.panels;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.animalclinic.controller.OwnerController;
import lk.ijse.animalclinic.controller.PaymentController;
import lk.ijse.animalclinic.core.dto.OwnerDTO;
import lk.ijse.animalclinic.core.dto.PaymentDTO;

/**
 *
 * @author chamindu
 */
public class ViewPaymentPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPaymentPanel
     */
    public ViewPaymentPanel() {
        initComponents();
        getAllPayments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPayID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPayments = new org.jdesktop.swingx.JXTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("pay.ID    -");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 130, 40));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(189, 103, 107));
        jLabel2.setText("     Remove");
        jLabel2.setToolTipText("");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 190, 180, 50));

        txtPayID.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtPayID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtPayID, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, 220, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1280, 240));

        tblPayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment Id", "Date", "Owner ID", "Owner Name", "Service Charge", "Treatmemnt Charge", "Medicine Charge", "Net Amount"
            }
        ));
        tblPayments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPaymentsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPayments);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void tblPaymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPaymentsMouseClicked
        String id=(String) tblPayments.getValueAt(tblPayments.getSelectedRow(),0);
        txtPayID.setText(id);
            
    }//GEN-LAST:event_tblPaymentsMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         try {
            String id=(String) tblPayments.getValueAt(tblPayments.getSelectedRow(),0);
            boolean result=PaymentController.removePayment(id);
            if (result) {
                JOptionPane.showMessageDialog(this, "Payment has been successfully Deleted.");
                getAllPayments();
            } else {
                JOptionPane.showMessageDialog(this, "Payment hasn't been deleted due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewPaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTable tblPayments;
    private javax.swing.JTextField txtPayID;
    // End of variables declaration//GEN-END:variables

    private void getAllPayments() {
        try {
            DefaultTableModel dtm = (DefaultTableModel)tblPayments.getModel();
            ArrayList<PaymentDTO> payments=PaymentController.getAllPayments();
            if(payments==null)return;
            dtm.setRowCount(0);
            for (PaymentDTO payment : payments) {
                OwnerDTO owner=OwnerController.searchOwnerByID(payment.getOID());
                Object[] rowCount={payment.getPaymentID(),payment.getPaymentDate(),payment.getOID(),owner.getFirstName(),payment.getServiceCharge(),payment.getTreatmentCharge(),payment.getMedicineCharge(),payment.getNetAmount()};
                dtm.addRow(rowCount);
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewPaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
}
